name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
      with:
        fetch-deph: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with: 
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: verlucho
      
    - name: Docker Login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        NEW_VERSION: ${{ steps.verlucho.outputs.version }}
      run: | 
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        echo "New Version $NEW_VERSION !!!!!!!!!"
            

    # - name: Construcción de Imagen
    #   run: |
    #     docker image build -t lukafran/docker-graphql:2.0.0 .
    #     docker image build -t lukafran/docker-graphql .

    # - name: Subiendo imagen a Docker Hub
    #   run: |
    #     docker push lukafran/docker-graphql:2.0.0
    #     docker push lukafran/docker-graphql

        
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
