name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
      with:
        fetch-deph: 0

    - name: Docker Login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: | 
        docker login -u $DOCKER_USER -p $DOCKER_PASS

    - name: Construcción de Imagen
      run: |
        docker image build -t lukafran/docker-graphql:2.0.0 .
        docker image build -t lukafran/docker-graphql .

    - name: Subiendo imagen a Docker Hub
      run: |
        docker push lukafran/docker-graphql:2.0.0
        docker push lukafran/docker-graphql

        
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
